version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .dockerenv:/.venv
      - .:/app
    ports:
    - "8080:8080"
  db:
    image: postgres:15
    restart: always
    platform: linux/x86_64  # M1 Macの場合必要
    environment:
      POSTGRES_DB: fastapi_db
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      TZ: 'Asia/Tokyo'
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - 5432:5432
volumes:
  postgres_data:
